### PR TITLE
Fix Peers List for iOS SDK v4  

### PR DESCRIPTION
**Pull request by magicwave**
PeersListView, developed for iOS v3.x, used `DittoPeer.address` to display  
connected peer data which broke with iOS v4.0.0, where `DittoConnection`  
`peer1` and `peer2` properties were changed to the Swift Data type.  This commit  
refactors Peers List feature to display local peer connections and list  
remote peers with the v4.x DittoSwift package.

### CODE REVIEW

**Comment by magicwave** [comment]
A note on all the commits. I started with the v4 branch and rebased onto main, which has had some updates since v4 was created. So all the previous commits in v4 were committed again in this branch in the rebase. I then made the updates fixing the peers list code for SDK v4. 

When I created the PR, the branch to merge into was set to main automatically and I didn't notice until later. When I changed the merge target to v4, two conflicts arose: the Xcode Package.resolved file deep in the xcshareddata  folder, which is of little consequence, but the Presence Viewer javascript file was different. I pushed a new commit resolving both of those to the v4 branch versions.

**Comment by kndoshn** [comment]
@magicwave Is it hard to do git cherry-pick to create a new PR?

**Comment by magicwave** [comment]
> @magicwave Is it hard to do git cherry-pick to create a new PR?
I don't think it would be hard. Cherry-pick would essentially be doing the rebase manually, although there would be greater risk of missing something, I think.

**Comment by kndoshn** [comment]
Are all these changes meant to be merged into `v4`?

image

**Comment by magicwave** [comment]
Closing in favor of #56

**Pull request closed without merging**
