### PR TITLE
Move DittoLogger.setLogFileURL(logFileURL) outside of ExportLogs

### LINKED ISSUE #67: Export Logs creates an empty file for the first attempt

### PR DESCRIPTION
**Pull request by texasRanger09**
fixes #67

### CODE REVIEW

**Comment by magicwave** [comment]
- What is the problem that is solved with this PR? I think this has been working; were we exporting blank log files?
- should the merge target be `main` branch instead of `v4`?

**Comment by texasRanger09** [comment]
@magicwave This fixes #67 

There is a race condition happening from when you set `DittoLogger.setLogFileURL` and Ditto starts writing to the log file with when the file is exported. The first time you export the logs the log file is blank because the file is exported before Ditto has a chance to start writing to the log file. When we move `DittoLogger.setLogFileURL` out of the `ExportLogs` tool this gives Ditto enough time to write logs to the file before it is exported.

**Comment by okdistribute** [comment]
We do not support `v4` branch anymore thankfully we merged that. So we can delete that branch to remove confusion?

`main` is v4 compatible. https://github.com/getditto/DittoSwiftTools/pull/64

**Review by kndoshn — APPROVED** [review]
I tested, and the issue seems fixed.

**Pull request merged**
