### PR TITLE
Use peerKeyString

### LINKED ISSUE #103: Swift - Update tools to use peerKeyString
Now that The 4.7.0 release of the Ditto SDK is live, we should change every tool that calculates the Ditto Peer to instead use the new `peerKeyString`.

Note this will require bumping the minimum Ditto SDK version for the tools to 4.7.0

### PR DESCRIPTION
**Pull request by bplattenburg**
Update to Ditto SDK 4.7.0 as the minimum requirement so that we can use `peerKeyString` instead of `peerKey` for expressing the Ditto Peer Key in it standard Base64 format.

Note - this does not update the usage in `PeersObserverVM`'s `connectionsWithLocalPeer` method because that uses a `DittoConnection` type which only has Peer Keys expressed as `Data`. Rather than manually hashing those, I think it makes sense to follow up with the SDKs team to see if those can be expressed as strings as well.

Closes #103

### CODE REVIEW

**Comment by bplattenburg** [comment]
Updating the `DittoConnection` type to support Peer Key Strings will be an SDK change, see https://github.com/getditto/ditto/pull/12799

**Review by texasRanger09 — APPROVED** [review]

**Comment by bplattenburg** [comment]
I'm intentionally not merging this yet so that we can integrate https://github.com/getditto/DittoSwiftTools/pull/108 in the POS/KDS demo app which is not yet updated to the 4.7.0 Ditto SDK.

**Comment by bplattenburg** [comment]
We're going to hold off on merging this at this time to keep the tools support for Ditto SDK 4.5.x

**Comment by bplattenburg** [comment]
This can now be merged

**Pull request merged**
