### PR TITLE
Fix ditto instance retain cycle in PresenceViewer

### PR DESCRIPTION
**Pull request by magicwave**
Working from Konstantine's fix in [monorepo](https://github.com/getditto/ditto/pull/10152/files#diff-e9c0cbddf72b763b74653917aa980f0d7c229f172d85250b57ea9bdb17a5da77) version, modified for current DittoSwiftTools version (from main branch fbf428dccc6384b154fd5c605e5432dbc835c748).

### CODE REVIEW

**Review by bplattenburg — APPROVED** [review]
LGTM, thanks!

**Comment by magicwave** [comment]
@bplattenburg  I'd would love to see this fix in a release, for a package version to be free from the crash issue it created for the builder app. At the same time, there is support for MacOS in the PresenceViewer module code. I built to the "My Mac (built for iPad)" simulator to test that code and it worked without crashing, however I'm not sure if that's sufficient testing to be confident of a release. Should we just merge it and see, or are there tests that should/would validate stability for intended supported platforms?

**Review by okdistribute — COMMENTED** [review]
This was already approved and merged to the monorepo but never made it here, so seems safe to merge.

We need to get this on the DittoPresenceViewer repo, looks like the source of truth is moving there

**Comment by magicwave** [comment]
> This was already approved and merged to the monorepo but never made it here, so seems safe to merge.
> We need to get this on the DittoPresenceViewer repo, looks like the source of truth is moving there
@okdistribute this is not a copy/paste of @konstantinbe's fix, which did not work out of the box. Thus, caution...

**Comment by bplattenburg** [comment]
@magicwave for the purposes of this repo, I think we can validate on iOS & tvOS, but we have currently deemed true mac support to be too much effort given no known customer usage. In the broken out presence viewer, it may be a much smaller lift to support mac - I'll test it out there.

I'll give this a quick sanity check locally, and if all is well will merge & release a new version (likely 7.0.1)

**Review by bplattenburg — APPROVED** [review]

**Comment by bplattenburg** [comment]
All works properly as far as I can tell, merging & releasing now

**Pull request merged**
