### PR TITLE
New peers list updated with a more detailed view for iOS 15+

### PR DESCRIPTION
**Pull request by magicwave**
New peers list updated with a more detailed view for iOS 15+

### CODE REVIEW

**Comment by kndoshn** [comment]
@magicwave Just curious about the context - which API does this make only support iOS 15 and above?

**Comment by phatblat** [comment]
I'm not able to get the new Peers List to populate but seeing the same problem with the Presence Viewer.

Screen Shot 2023-03-22 at 6 15 51 PM

Regarding the "BLE approximate distance is inaccurate." note, we actually removed that feature from the Presence Viewer getditto/ditto#6955 because there were many issues with it, plus it was distracting to customers.

**Review by phatblat — APPROVED** [review]
UI looks good even on an iPod touch!

**Comment by magicwave** [comment]
> I'm not able to get the new Peers List to populate but seeing the same problem with the Presence Viewer (even with two devices next to each other).
> 
> Screen Shot 2023-03-22 at 6 15 51 PM
> 
> Regarding the "BLE approximate distance is inaccurate." note, we actually removed that feature from the Presence Viewer [getditto/ditto#6955](https://github.com/getditto/ditto/issues/6955) because there were many issues with it, plus it was distracting to customers.

There is a trick running the standalone DittoToolsApp, which is that you have to navigate to the "Change Identity" view and enter appID/token and then hit "Restart Ditto". This will enable syncing and the peers list should populate.

**Comment by okdistribute** [comment]
We are going to implement this in javascript as well so this may not get much usage but more code on the tools is better than less so I believe we should be OK to merge this. It's more of a starting place for someone else to incorporate into their app rather than a full-baked solution.

**Pull request merged**
