### PR TITLE
Reconcile v3 -> v4 branches

### PR DESCRIPTION
**Pull request by magicwave**
The `v3` branch (currently `main`) and `v4` branches diverged, where features were added to v3 and not to v4 and vice versa. However, simply cherry-picking feature and fix commits across to v4 is not feasible because of v4 breaking changes. A previous PR attempted to fix this by rebasing all of v4 onto v3 and resolving conflicts, however this introduced a huge number of new commits owing to re-committing all previous commits.  

This branch was constructed by cherry-picking non-duplicate v4 branch commits, cleaning up as needed. The result is that this branch should become the canonical v4 branch, where all features work in both SDK v3/v4 versions.

Note that this branch should not be merged to main until it is decided to drop support of v3.

### CODE REVIEW

**Comment by okdistribute** [comment]
Nice!

**Review by kndoshn — APPROVED** [review]

**Review by okdistribute — APPROVED** [review]

**Comment by okdistribute** [comment]
Since the number of customers left on v3 is 2, we can probably reach out to each of them individually and notify them of this change, then merge the branch. What do you think @magicwave ?

**Comment by magicwave** [comment]
> Since the number of customers left on v3 is 2, we can probably reach out to each of them individually and notify them of this change, then merge the branch. They would need to change their dependency target in their iOS app to the v3 branch or v3 < 4.0.0 in their Package.resolved. What do you think @magicwave ?

Let me try the v3 package setting. I think I remember having trouble getting it to resolve when I first started digging into it. AFIK, only Alaska is still on v3 due to the New Relic/PLCrashReporter issue. If a tagged commit doesn't work for v3 we should probably be able to create a tag on a known working v3 commit and let that be the official v3 support.

**Comment by okdistribute** [comment]
Great!

**Comment by okdistribute** [comment]
Sounds like we can merge this if we reach out to alaska and let them know, right?

**Comment by magicwave** [comment]
Closed in favor of v4.4.0 branch merged to main

**Pull request closed without merging**
